defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Shipeng Xie 
subtitle: AI+XR Researcher

# Side Menu Links
menu:
  - text: My Profile
    link: /
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

  - text: My Resume
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/shipeng-xie-13262a187/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/sirius-xie/
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/shipeng.xie.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/shipeng.xie
    icon: fab fa-twitter


    
